b3_dwm_user:
    resource: "@B3DWMUserBundle/Resources/config/routing.yml"
    prefix:   /

b3_dwm_article:
    resource: "@B3DWMArticleBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
